spring.application.name=SideTest
spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.reactive.function=TRACE
spring.codec.max-in-memory-size=500MB

